resource "aws_instance" "instance" {
  ami                         = var.ami
  instance_type               = var.instance
#  key_name                    = "key"
  vpc_security_group_ids      = [aws_security_group.security.id]
  subnet_id                   = aws_subnet.subnet.id
  associate_public_ip_address = true


    user_data = file("install_jenkins.sh")

  tags = {
    Name = "${var.name}-instance"
  }
}

resource "aws_key_pair" "inst-key" {
  key_name   = "login"
  public_key = tls_private_key.instance-key.public_key_openssh
}

resource "tls_private_key" "instance-key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}
provisioner "local-exec" {
  command = <<-EOT
      sudo echo '${tls_private_key.instance-key.private_key_pem}' > ./vi'${login}'.pem
      sudo chmod 400 ./'${login}'.pem
    EOT
}

#
#resource "tls_private_key" "dev_key" {
#  algorithm = "RSA"
#  rsa_bits  = 4096
#}
#resource "aws_key_pair" "generated_key" {
#  key_name   = var.generated_key_name
#  public_key = tls_private_key.dev_key.public_key_openssh

#  provisioner "local-exec" {    # Generate "terraform-key-pair.pem" in current directory
#    command = <<-EOT
#      echo '${tls_private_key.dev_key.private_key_pem}' > ./'${var.generated_key_name}'.pem
#      chmod 400 ./'${var.generated_key_name}'.pem
#    EOT
#  }
#
#  variable "generated_key_name" {
#    type        = string
#    default     = "terraform-key-pair"
#    description = "Key-pair generated by Terraform"
#  }
